{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-txcutr
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/mfansler/txcutr
  git_tag: v0.1.0-alpha

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base  {{ r_base }}
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-rtracklayer

  run:
    - r-base
    - bioconductor-annotationdbi
    - bioconductor-biocgenerics
    - bioconductor-biocparallel
    - bioconductor-biostrings
    - bioconductor-genomicfeatures
    - bioconductor-genomicranges
    - bioconductor-iranges
    - bioconductor-s4vectors
    - bioconductor-rtracklayer

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('txcutr')"           # [not win]
    - "\"%R%\" -e \"library('txcutr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/mfansler/txcutr
  license: GPL-3
  summary: Methods for generating truncated transcriptome annotations and indexable sequences.

  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

# The original CRAN metadata for this package was:

# Package: txcutr
# Title: Transcriptome CutUTR
# Description: Methods for generating truncated transcriptome annotations and indexable sequences.
# Version: 0.1.0
# Authors@R: person(given = "Mervin", family = "Fansler", role = c("aut", "cre"), email = "mef3005@med.cornell.edu", comment = c(ORCID = "0000-0002-4108-4218"))
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# Imports: AnnotationDbi, GenomicFeatures, IRanges, GenomicRanges, BiocGenerics, Biostrings, S4Vectors, rtracklayer, BiocParallel, methods
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 7.1.1

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml
